version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: run
          command: ssh -p 22 Nuxt3Blog@18.178.115.226 "~/bin/build-and-start"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
